namespace: helmtest

frontend:
    service:
         serviceType: LoadBalancer
         port: 80
         targetPort: 80
    deployment:
         replicas: 1
         #image: mreferre/yelb-ui:0.3
         image: ec2-35-154-147-30.ap-south-1.compute.amazonaws.com/cna-day/yelb-ui:1.0
         containerPort: 80
cache:
    service:
         serviceType: ClusterIP
         port: 6379
    deployment:
         replicas: 1
         #image: redis:4.0.2
         image: ec2-35-154-147-30.ap-south-1.compute.amazonaws.com/cna-day/yelb-cache:1.0
         containerPort: 6379

appserver:
    service:
         serviceType: ClusterIP
         port: 4567
    deployment:
         replicas: 1
         image: mreferre/yelb-appserver:0.3
         #image: ec2-35-154-147-30.ap-south-1.compute.amazonaws.com/cna-day/yelb-appserver:1.0
         containerPort: 4567
db:
    service:
         serviceType: ClusterIP
         port: 5432
    deployment:
         replicas: 1
         #image: mreferre/yelb-db:0.3
         image: ec2-35-154-147-30.ap-south-1.compute.amazonaws.com/cna-day/yelb-db:1.0
         containerPort: 5432
