apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-server
  labels:
    app: redis-server
    tier: cache
spec:
  type: {{ .Values.cache.service.serviceType }}
  ports:
  - port: {{ .Values.cache.service.port }}
  selector:
    app: redis-server
    tier: cache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-server
spec:
  replicas: {{ .Values.cache.deployment.replicas }}
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server
        image: {{ .Values.cache.deployment.image }}
        ports:
        - containerPort: {{ .Values.cache.deployment.containerPort }} 
