apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
spec:
  type: {{ .Values.frontend.service.serviceType }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: yelb-ui
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: yelb-ui
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  template:
    metadata:
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
      - name: yelb-ui
        image:  {{ .Values.frontend.deployment.image }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.containerPort }}
